import type { Metadata } from 'next';
import './globals.css';
import NextAuthProvider from '@/lib/nextauth/next-auth-provider';
import { QueryProvider } from '@/providers';

export const metadata: Metadata = {
  title: 'Finance',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <QueryProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
