import type { Metadata } from 'next';
import AppLayoutClient from './layout.client';
import { getServerUser } from '@/lib/getServerUser';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function AppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getServerUser();

  if (!user) redirect('/signin');
  return (
    <>
      <AppLayoutClient>{children}</AppLayoutClient>
    </>
  );
}
