import type { Metadata } from 'next';
import AppLayoutClient from './layout.client';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <AppLayoutClient>{children}</AppLayoutClient>
    </>
  );
}
